### ISSUE TITLE
Ignore D412 (`blank-lines-between-header-and-content`)  if a reStructuredText directive follows a section header

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#11577]
Originally found in https://github.com/pytest-dev/pytest/pull/12375 where I was trying to fix pytest's API reference. The following code violates `D412`, but sphinx doesn't render the docstring correctly if the blank line after `Example:` is removed.

```python
# violates D412

def f():
    """
    Example:

    .. code-block:: python

        import foo
    """
```

Autofixed code:

```python
# doesn't violate D412, but sphinx fails to render correctly

def f():
    """
    Example:
    .. code-block:: python

        import foo
    """
```

![image](https://github.com/astral-sh/ruff/assets/17039389/03c5b34c-7969-4e27-b78d-ecd97b188017)

Repro on playground: https://play.ruff.rs/b4c94827-8503-4568-978d-59e74a31a01b

**Comment by harupy** [comment]
@charliermarsh I think any directive can cause the same issue. For example:

```
def f():
    """
    Example:
    .. note::
        
        This example only works on windows.

    .. code-block:: python

        import foo
    """
```

**Comment by dhruvmanila** [comment]
I think this is resolved by #11609, @charliermarsh feel free to re-open if it's not complete.

**Comment by reubano** [comment]
Still broken for doctests.

```python
class MyClass:
    """
    Examples:

        >>> def db():
        ...     yield object()
        >>> db()
        <generator object db at ...>

    """
```

And disabling the rule doesn't add the empty line back if another ruff process removes it.
