### ISSUE TITLE
N817 not correctly detecting `from xml.etree import ElementTree as ET`

### ISSUE THREAD

**Issue by lengau** [astral-sh/ruff#12940]
In ruff 0.6.1, this file:

```python
from xml.etree import ElementTree as ET

_ = ET
```

causes N817 to trigger an error with the default ruff settings,even though the default value of `lint.flake8-import-conventions` contains that mapping and it's supposed to be ignored according to [the docs](https://docs.astral.sh/ruff/rules/camelcase-imported-as-acronym/).

```
$ ruff check --fix --unsafe-fixes --select ICN001,N817 sample.py 
sample.py:2:23: N817 CamelCase `ElementTree` imported as acronym `ET`
  |
2 | from xml.etree import ElementTree as ET
  |                       ^^^^^^^^^^^^^^^^^ N817
3 | 
4 | _ = ET
  |

Found 1 error.
```

```python
import xml.etree.ElementTree as ET

_ = ET
```

failed in 0.6.0 but is fixed in 0.6.1

**Comment by MichaReiser** [comment]
Thanks for reporting. This was fixed in 0.6.1. Can you try upgrading?

**Comment by lengau** [comment]
Thanks! I saw the 0.6.1 upgrade after reporting and will do so as soon as my [build completes](https://github.com/snapcrafters/ruff/actions/runs/10424701636/job/28874026510)

**Comment by lengau** [comment]
@MichaReiser thanks for the quick turnaround! I've amended the bug report, as the `from ... import ... as ...` form still fails.

I personally consider it low priority since I've just gone ahead and changed them to `import ... as ...` and let the auto-fixer fix them :-)

**Comment by MichaReiser** [comment]
Ohh I see. Thanks for updating the issue and sorry for the oversight

**Comment by lengau** [comment]
That was quick! Thank you!
